# ==========================================================
# Spring Boot Application
# ==========================================================
spring.application.name=migracao_dados_to_db

# ==========================================================
# DATASOURCE: SPRING BATCH (JobRepository)
# ==========================================================
spring.datasource.jdbc-url=jdbc:mysql://localhost:33010/spring_batch_jobrepository?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=1234567
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Inicialização do schema para Spring Batch
spring.batch.jdbc.initialize-schema=always
spring.sql.init.mode=always

# ==========================================================
# DATASOURCE: PESSOA (Aplicação principal)
# ==========================================================
app.datasource.jdbc-url=jdbc:mysql://localhost:3311/spring_batch_db1?allowPublicKeyRetrieval=true&useSSL=false
app.datasource.username=root
app.datasource.password=1234567

# ==========================================================
# SFTP SERVER CONFIGURATION
# ==========================================================
sftp.host=localhost
sftp.port=2222
sftp.user=batch
sftp.password=batch123

# ==========================================================
# SFTP REMOTE DIRECTORY
# ==========================================================
# Diretório no servidor SFTP de onde você vai baixar os arquivos
sftp.dir.remote.download=/source


# ==========================================================
# LOCAL TEMP DIRECTORY
# ==========================================================
# Pasta base para armazenar os dados baixados do SFTP localmente
sftp.dir.local.download=${user.home}/pessoas-data

# Padrão para localizar CSVs (se algum dia quiser usar MultiResourceItemReader)
app.filial-report-pattern=file:${sftp.dir.local.download}/*.csv