spring.application.name=sb-writer-FlatFileItemWriter-FlatCustomizado

### DATASOURCE: SPRING BATCH
spring.datasource.jdbcUrl = jdbc:mysql://localhost:33010/spring_batch_jobrepository?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username = root
spring.datasource.password = 1234567

### DATASOURCE: LANCAMENTO
app.datasource.jdbcUrl = jdbc:mysql://localhost:3311/spring_batch_db1?allowPublicKeyRetrieval=true&useSSL=false
app.datasource.username = root
app.datasource.password = 1234567

