networks:
  spring-batch-network:
    driver: bridge

volumes:
  mysql-spring-batch-jobrepository:
  mysql-spring-batch-db1:
  mysql-spring-batch-db2:

# ====================================================================================================================
# Mysql - Spring Batch Metadados
# ====================================================================================================================
services:
  mysql-spring-batch-jobrepository:
    image: mysql:8.0
    container_name: mysql-spring-batch-jobrepository
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234567
      MYSQL_DATABASE: spring_batch_jobrepository
      TZ: "America/Sao_Paulo"
    ports:
      - "33010:3306"
    volumes:
      - mysql-spring-batch-jobrepository:/var/lib/mysql
    networks:
      - spring-batch-network
    profiles:
      - spring-batch-jobrepository

# ====================================================================================================================
# Mysql - Spring Batch DB1
# ====================================================================================================================
  mysql-spring-batch-DB1:
    image: mysql:8.0
    container_name: mysql-spring-batch-DB1
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234567
      MYSQL_DATABASE: spring_batch_db1
      TZ: "America/Sao_Paulo"
    ports:
      - "3311:3306"
    volumes:
      - mysql-spring-batch-db1:/var/lib/mysql
    networks:
      - spring-batch-network
    profiles:
      - spring-batch-DB1

  # ====================================================================================================================
  # Mysql - Spring Batch DB2
  # ====================================================================================================================
  mysql-spring-batch-DB2:
    image: mysql:8.0
    container_name: mysql-spring-batch-DB2
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234567
      MYSQL_DATABASE: spring_batch_db2
      TZ: "America/Sao_Paulo"
    ports:
      - "3312:3306"
    volumes:
      - mysql-spring-batch-db2:/var/lib/mysql
    networks:
      - spring-batch-network
    profiles:
      - spring-batch-DB2
