spring.application.name=SbDistributedTransactions

# ========= JOB REPOSITORY (SPRING BATCH) - NÃO XA =========
spring.datasource.jdbcUrl=jdbc:mysql://localhost:33010/spring_batch_jobrepository?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234567
spring.batch.jdbc.initialize-schema=always

# ========= DATASOURCE XA 1 =========
app1.datasource.xa-properties.url=jdbc:mysql://localhost:3311/spring_batch_db1?allowPublicKeyRetrieval=true&useSSL=false&pinGlobalTxToPhysicalConnection=true&serverTimezone=UTC
app1.datasource.xa-properties.user=root
app1.datasource.xa-properties.password=1234567

# ========= DATASOURCE XA 2 =========
app2.datasource.xa-properties.url=jdbc:mysql://localhost:3312/spring_batch_db2?allowPublicKeyRetrieval=true&useSSL=false&pinGlobalTxToPhysicalConnection=true&serverTimezone=UTC
app2.datasource.xa-properties.user=root
app2.datasource.xa-properties.password=1234567



# ========= CONFIGURAÇÕES GLOBAIS DO ATOMIKOS =========
com.atomikos.icatch.log_base_dir=./transaction-logs
com.atomikos.icatch.max_timeout=300000
com.atomikos.icatch.default_max_wait_time_on_shutdown=60000
com.atomikos.icatch.threaded_2pc=true