spring.application.name = spring-batch

### ============================
### DATASOURCE: SPRING BATCH
### (JobRepository / StepExecution / JobExecution)
### ============================
spring.datasource.batch.jdbcUrl = jdbc:mysql://localhost:3307/spring_batch?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.batch.username = root
spring.datasource.batch.password = 1234567

# Criação automática das tabelas do Spring Batch
spring.batch.jdbc.initialize-schema = always
spring.sql.init.mode = always


### ============================
### DATASOURCE: BUSINESS
### (Banco de dados do domínio de negócio)
### ============================
app.datasource.business.jdbcUrl = jdbc:mysql://localhost:3308/spring_batch_businnes?allowPublicKeyRetrieval=true&useSSL=false
app.datasource.business.username = root
app.datasource.business.password = 1234567
